APP = cross
HW = x86

include hw/$(HW).mk
include cpu/$(CPU).mk
include arch/$(ARCH).mk

include mk/dirs.mk
include mk/pack_cross.mk
include mk/gz.mk
include mk/src.mk
include mk/cfg.mk
include mk/cclibs.mk
include mk/binutils.mk
include mk/gcc.mk
include mk/libc.mk
